const Booking = require('../models/Booking');
const Sale = require('../models/Sale');
const GymMember = require('../models/GymMember');
const IncomeEntry = require('../models/IncomeEntry');
const ExpenseEntry = require('../models/ExpenseEntry');
const LedgerEntry = require('../models/LedgerEntry');
const Shift = require('../models/Shift');
const PurchaseRequest = require('../models/PurchaseRequest');
const asyncHandler = require('../middleware/asyncHandler');
const { ApiError } = require('../middleware/errorHandler');

function fmtDate(d) {
  if (!d) return new Date().toISOString().split('T')[0];
  try { return new Date(d).toISOString().split('T')[0]; } catch (e) { return String(d); }
}

function lagosDate(d) {
  if (!d) d = new Date();
  try {
    return new Date(d).toLocaleDateString('sv-SE', { timeZone: 'Africa/Lagos' });
  } catch (e) { return fmtDate(d); }
}

function parsePaymentDate(str) {
  if (!str) return '';
  // Already YYYY-MM-DD
  if (/^\d{4}-\d{2}-\d{2}/.test(str)) return str.slice(0, 10);
  // DD/MM/YY or DD/MM/YYYY from todayDDMMYY()
  const parts = str.split('/');
  if (parts.length === 3) {
    const dd = parts[0].padStart(2, '0');
    const mm = parts[1].padStart(2, '0');
    let yy = parts[2];
    if (yy.length === 2) yy = '20' + yy;
    return yy + '-' + mm + '-' + dd;
  }
  // Try Date parse as fallback
  const d = new Date(str);
  if (!isNaN(d.getTime())) return fmtDate(d);
  return str;
}

async function aggregateRoomRevenue(from, to) {
  // Fetch bookings with guest, but limit to those with payments to avoid OOM on vacant-heavy DB
  const bookings = await Booking.find({ guest: { $ne: '' } }).lean();
  const rows = [];
  for (const b of bookings) {
    const payments = b.payments || [];
    if (payments.length) {
      for (const p of payments) {
        const amt = Number(p.amount) || 0;
        if (amt <= 0) continue;
        const rawDate = p.ts ? lagosDate(new Date(Number(p.ts))) : (p.date || b.checkin);
        const payDate = parsePaymentDate(rawDate) || lagosDate(b.createdAt || Date.now());
        if (!payDate) continue;
        if (from && payDate < from) continue;
        if (to && payDate > to) continue;
        rows.push({
          id: 'auto-room-' + b.room + '-' + (p.id || p.ts || payDate) + '-' + amt,
          date: payDate,
          department: 'Rooms & Bookings',
          description: 'Room ' + b.room + ' — ' + b.guest,
          amount: amt,
          method: p.mode || b.payMethod || '',
          recordedBy: p.by || b.recordedBy || 'System',
          autoGenerated: true,
          source: 'booking',
        });
      }
    } else if (Number(b.paid) > 0) {
      // Legacy bookings with no payments array but paid field
      const payDate = parsePaymentDate(b.checkin) || lagosDate(b.createdAt || Date.now());
      if (!payDate) continue;
      if (from && payDate < from) continue;
      if (to && payDate > to) continue;
      rows.push({
        id: 'auto-room-' + b.room + '-' + payDate + '-legacy',
        date: payDate,
        department: 'Rooms & Bookings',
        description: 'Room ' + b.room + ' — ' + b.guest,
        amount: Number(b.paid),
        method: b.payMethod || '',
        recordedBy: b.recordedBy || 'System',
        autoGenerated: true,
        source: 'booking',
      });
    }
  }
  return rows;
}

async function aggregateOutletRevenue(from, to, deptFilter, deptLabel) {
  const match = { department: deptFilter, status: 'completed' };
  if (from || to) {
    match.createdAt = {};
    if (from) match.createdAt.$gte = new Date(from + 'T00:00:00+01:00');
    if (to) match.createdAt.$lte = new Date(to + 'T23:59:59.999+01:00');
  }
  const sales = await Sale.find(match);
  return sales.map(s => {
    const totalProcurementCost = (s.items || []).reduce((sum, item) => {
      return sum + (Number(item.cost) || 0) * (Number(item.qty) || 0);
    }, 0);
    return {
      id: 'auto-' + deptFilter + '-' + s._id,
      date: lagosDate(s.createdAt),
      department: deptLabel,
      description: (s.items || []).map(i => i.name + ' ×' + i.qty).join(', ') || deptLabel + ' sale',
      amount: s.total || 0,
      method: s.method || '',
      recordedBy: s.waiter || s.staff || 'System',
      autoGenerated: true,
      source: deptFilter,
      procurementIds: [...new Set((s.items || []).map(i => i.procurementId).filter(Boolean))],
      cost: totalProcurementCost,
    };
  }).filter(e => e.amount > 0);
}

async function aggregateGymRevenue(from, to) {
  const members = await GymMember.find({});
  const rows = [];
  for (const m of members) {
    const payments = m.payments || [];
    if (!payments.length) continue;
    for (const p of payments) {
      const amt = Number(p.amount) || 0;
      if (amt <= 0) continue;
      const rawDate = p.date || m.joined || lagosDate(m.createdAt || Date.now());
      const payDate = parsePaymentDate(rawDate) || lagosDate(m.createdAt || Date.now());
      if (from && payDate < from) continue;
      if (to && payDate > to) continue;
      rows.push({
        id: 'auto-gym-' + (m._id || '').toString().slice(-8) + '-' + (p.ts || payDate),
        date: payDate,
        department: 'Gym',
        description: 'Membership — ' + m.name + (m.planName ? ' (' + m.planName + ')' : ''),
        amount: amt,
        method: p.mode || 'Cash',
        recordedBy: p.by || 'Gym Attendant',
        autoGenerated: true,
        source: 'gym',
      });
    }
  }
  return rows;
}

exports.pnl = asyncHandler(async (req, res) => {
  const { from, to, mode } = req.query;
  const isShift = mode !== 'calendar';

  // Get shift start hour from Config
  let shiftStart = 9;
  try {
    const Config = require('../models/Config');
    const cfg = await Config.findOne();
    if (cfg && typeof cfg.shiftStartHour === 'number') shiftStart = cfg.shiftStartHour;
  } catch (err) {
    console.error('[Accounting] Failed to load shift start hour from Config:', err.message);
  }

  function shiftKey(dateStr) {
    if (!isShift) return dateStr;
    const d = /^\d{4}-\d{2}-\d{2}$/.test(dateStr) ? new Date(dateStr + 'T12:00:00') : new Date(dateStr);
    if (isNaN(d.getTime())) return dateStr;
    if (d.getHours() < shiftStart) d.setDate(d.getDate() - 1);
    return lagosDate(d);
  }

  const safeAgg = (fn, label) => fn().catch(err => { console.error(`[Accounting] ${label} aggregation failed:`, err.message); return []; });

  // Manual income: apply date filter
  const manualMatch = { autoGenerated: { $ne: true } };
  if (from || to) {
    manualMatch.date = {};
    if (from) manualMatch.date.$gte = from;
    if (to) manualMatch.date.$lte = to;
  }
  // Manual expenses: apply date filter
  const expenseMatch = {};
  if (from || to) {
    expenseMatch.date = {};
    if (from) expenseMatch.date.$gte = from;
    if (to) expenseMatch.date.$lte = to;
  }

  const [roomIncome, restIncome, poolIncome, gymIncome, manualIncome, expenses, cogsSales] = await Promise.all([
    safeAgg(() => aggregateRoomRevenue(from, to), 'Room Revenue'),
    safeAgg(() => aggregateOutletRevenue(from, to, 'restaurant', 'Restaurant'), 'Restaurant Revenue'),
    safeAgg(() => aggregateOutletRevenue(from, to, 'poolbar', 'Pool Bar'), 'Pool Bar Revenue'),
    safeAgg(() => aggregateGymRevenue(from, to), 'Gym Revenue'),
    IncomeEntry.find(manualMatch).sort({ date: -1 }).catch(err => { console.error('[Accounting] Manual income query failed:', err.message); return []; }),
    ExpenseEntry.find(expenseMatch).sort({ date: -1 }).catch(err => { console.error('[Accounting] Expense query failed:', err.message); return []; }),
    Sale.find({ department: { $in: ['restaurant', 'poolbar'] }, status: 'completed', ...(from || to ? { createdAt: { ...(from ? { $gte: new Date(from) } : {}), ...(to ? { $lte: new Date(to + 'T23:59:59.999Z') } : {}) } } : {}) }).catch(err => { console.error('[Accounting] COGS query failed:', err.message); return []; }),
  ]);

  // ── Income: aggregate to one row per (shift/calendar day, department) ──
  console.log('[Accounting pnl] raw counts:', { roomIncome: roomIncome.length, restIncome: restIncome.length, poolIncome: poolIncome.length, gymIncome: gymIncome.length, manualIncome: manualIncome.length, mode: isShift ? 'shift' : 'calendar', from: from || '-', to: to || '-' });
  roomIncome.slice(0,3).forEach(r => console.log('[Accounting pnl] roomIncome sample:', JSON.stringify(r)));
  restIncome.slice(0,3).forEach(r => console.log('[Accounting pnl] restIncome sample:', JSON.stringify(r)));
  const DEPT_MAP = { 'Rooms & Bookings': 'Front Desk', 'Restaurant': 'Restaurant', 'Pool Bar': 'Pool Bar', 'Gym': 'Gym' };
  const incomeRows = [...roomIncome, ...restIncome, ...poolIncome, ...gymIncome, ...manualIncome.map(e => ({
    id: e._id ? e._id.toString() : e.id, date: fmtDate(e.date), department: e.department || 'Other', amount: e.amount || 0, autoGenerated: false, source: e.source || 'manual', description: e.description || '', method: e.method || '', recordedBy: e.recordedBy || '',
  }))];
  console.log('[Accounting pnl] incomeRows total:', incomeRows.length);

  // Return detailed per-transaction income so dashboard Recent Transactions and shift totals see each sale/booking individually
  const income = incomeRows
    .filter(r => r.amount && r.amount > 0)
    .map(r => {
      const dept = DEPT_MAP[r.department] || r.department || 'Other';
      const d = shiftKey(r.date);
      return {
        id: r.id || (d + '|' + dept + '-' + Math.random().toString(36).slice(2,6)),
        date: d,
        department: dept,
        amount: Number(r.amount) || 0,
        source: r.source || (dept === 'Front Desk' ? 'booking' : dept === 'Restaurant' ? 'Restaurant' : dept === 'Pool Bar' ? 'Poolbar' : dept === 'Gym' ? 'gym' : 'manual'),
        description: r.description || '',
        method: r.method || '',
        recordedBy: r.recordedBy || '',
        autoGenerated: r.autoGenerated !== undefined ? r.autoGenerated : true,
      };
    })
    .sort((a, b) => b.date.localeCompare(a.date) || a.department.localeCompare(b.department));
  console.log('[Accounting pnl] detailed income:', income.length, income.slice(0,5).map(r => r.date + '|' + r.department + '=' + r.amount + ' ' + (r.description||'').slice(0,20)));

  // ── Expenses: COGS (from restaurant/poolbar sales) + manual batch per day (expandable) ──
  const cogsByDate = {};
  for (const s of cogsSales) {
    const key = shiftKey(lagosDate(s.createdAt));
    const cogs = (s.items || []).reduce((sum, it) => {
      if (Number(it.cost) > 0) return sum + Number(it.cost) * (Number(it.qty) || 0);
      return sum;
    }, 0);
    if (cogs <= 0) continue; // skip sales with no stored cost (manual cost needed)
    if (!cogsByDate[key]) cogsByDate[key] = 0;
    cogsByDate[key] += cogs;
  }

  const manualExpByDate = {};
  const manualExpItems = {};
  for (const e of expenses) {
    const key = shiftKey(fmtDate(e.date));
    if (!manualExpByDate[key]) { manualExpByDate[key] = 0; manualExpItems[key] = []; }
    manualExpByDate[key] += Number(e.amount) || 0;
    manualExpItems[key].push({ id: e._id.toString(), date: e.date, category: e.category, expenditure: e.category, description: e.description, amount: Number(e.amount) || 0, recordedBy: e.recordedBy || '' });
  }

  const allDates = [...new Set([...Object.keys(cogsByDate), ...Object.keys(manualExpByDate)])];
  const expensesOut = allDates.map(date => ({
    date,
    cogs: cogsByDate[date] || 0,
    procurement: cogsByDate[date] || 0,
    manual: manualExpByDate[date] || 0,
    manualItems: manualExpItems[date] || [],
    total: (cogsByDate[date] || 0) + (manualExpByDate[date] || 0),
  })).sort((a, b) => b.date.localeCompare(a.date));

  const totalIncome = income.reduce((s, r) => s + r.amount, 0);
  const totalExpenses = expensesOut.reduce((s, r) => s + r.total, 0);

  res.json({ success: true, income, expenses: expensesOut, totalIncome, totalExpenses });
});

exports.addIncome = asyncHandler(async (req, res) => {
  const amt = Number(req.body.amount);
  if (isNaN(amt) || amt <= 0 || amt > 1e12) return res.status(400).json({ success: false, error: 'Amount must be > 0' });
  const entry = await IncomeEntry.create({
    date: req.body.date,
    department: String(req.body.department).trim(),
    description: String(req.body.description).trim().slice(0, 500),
    amount: amt,
    method: req.body.method ? String(req.body.method).trim() : '',
    recordedBy: req.body.recordedBy ? String(req.body.recordedBy).trim() : (req.user ? req.user.name : 'Accountant'),
    autoGenerated: false,
    source: 'manual',
  });
  res.status(201).json({
    success: true,
    data: {
      id: entry._id.toString(),
      date: fmtDate(entry.date),
      department: entry.department,
      description: entry.description,
      amount: entry.amount,
      method: entry.method,
      recordedBy: entry.recordedBy,
      autoGenerated: false,
      source: 'manual',
    },
  });
});

exports.updateIncome = asyncHandler(async (req, res) => {
  const existing = await IncomeEntry.findById(req.params.id);
  if (!existing) return res.status(404).json({ success: false, error: 'Income entry not found' });
  if (existing.autoGenerated) return res.status(403).json({ success: false, error: 'Auto-generated income cannot be edited' });
  const updates = {};
  if (req.body.date !== undefined) updates.date = req.body.date;
  if (req.body.department !== undefined) updates.department = String(req.body.department).trim();
  if (req.body.description !== undefined) updates.description = String(req.body.description).trim().slice(0, 500);
  if (req.body.amount !== undefined) {
    const amt = Number(req.body.amount);
    if (isNaN(amt) || amt <= 0 || amt > 1e12) return res.status(400).json({ success: false, error: 'Amount must be > 0' });
    updates.amount = amt;
  }
  if (req.body.recordedBy !== undefined) updates.recordedBy = String(req.body.recordedBy).trim();
  const entry = await IncomeEntry.findByIdAndUpdate(req.params.id, updates, { new: true, runValidators: true });
  res.json({
    success: true,
    data: {
      id: entry._id.toString(),
      date: fmtDate(entry.date),
      department: entry.department,
      description: entry.description,
      amount: entry.amount,
      method: entry.method,
      recordedBy: entry.recordedBy,
      autoGenerated: false,
      source: 'manual',
    },
  });
});

exports.deleteIncome = asyncHandler(async (req, res) => {
  const existing = await IncomeEntry.findById(req.params.id);
  if (!existing) return res.status(404).json({ success: false, error: 'Income entry not found' });
  if (existing.autoGenerated) return res.status(403).json({ success: false, error: 'Auto-generated income cannot be deleted' });
  await IncomeEntry.findByIdAndDelete(req.params.id);
  res.json({ success: true, message: 'Income entry deleted' });
});

exports.addExpense = asyncHandler(async (req, res) => {
  const amt = Number(req.body.amount);
  if (isNaN(amt) || amt <= 0 || amt > 1e12) return res.status(400).json({ success: false, error: 'Amount must be > 0' });
  const entry = await ExpenseEntry.create({
    date: req.body.date,
    category: String(req.body.category || req.body.expenditure || '').trim(),
    description: String(req.body.description).trim().slice(0, 500),
    amount: amt,
    recordedBy: req.body.recordedBy ? String(req.body.recordedBy).trim() : (req.user ? req.user.name : 'Accountant'),
  });
  res.status(201).json({
    success: true,
    data: {
      id: entry._id.toString(),
      date: fmtDate(entry.date),
      category: entry.category,
      description: entry.description,
      amount: entry.amount,
      recordedBy: entry.recordedBy,
    },
  });
});

exports.updateExpense = asyncHandler(async (req, res) => {
  const existing = await ExpenseEntry.findById(req.params.id);
  if (!existing) return res.status(404).json({ success: false, error: 'Expense entry not found' });
  const updates = {};
  if (req.body.date !== undefined) updates.date = req.body.date;
  if (req.body.category !== undefined || req.body.expenditure !== undefined) updates.category = String(req.body.category || req.body.expenditure).trim();
  if (req.body.description !== undefined) updates.description = String(req.body.description).trim().slice(0, 500);
  if (req.body.amount !== undefined) {
    const amt = Number(req.body.amount);
    if (isNaN(amt) || amt <= 0 || amt > 1e12) return res.status(400).json({ success: false, error: 'Amount must be > 0' });
    updates.amount = amt;
  }
  if (req.body.recordedBy !== undefined) updates.recordedBy = String(req.body.recordedBy).trim();
  const entry = await ExpenseEntry.findByIdAndUpdate(req.params.id, updates, { new: true, runValidators: true });
  res.json({
    success: true,
    data: {
      id: entry._id.toString(),
      date: fmtDate(entry.date),
      category: entry.category,
      description: entry.description,
      amount: entry.amount,
      recordedBy: entry.recordedBy,
    },
  });
});

exports.deleteExpense = asyncHandler(async (req, res) => {
  const entry = await ExpenseEntry.findByIdAndDelete(req.params.id);
  if (!entry) return res.status(404).json({ success: false, error: 'Expense entry not found' });
  res.json({ success: true, message: 'Expense entry deleted' });
});

exports.summary = asyncHandler(async (req, res) => {
  const [roomRows, restRows, poolRows, gymRows, manualIncome, manualExpenses] = await Promise.all([
    aggregateRoomRevenue(null, null),
    aggregateOutletRevenue(null, null, 'restaurant', 'Restaurant'),
    aggregateOutletRevenue(null, null, 'poolbar', 'Pool Bar'),
    aggregateGymRevenue(null, null),
    IncomeEntry.find({}).lean(),
    ExpenseEntry.find({}).lean(),
  ]);
  const autoIncome = [...roomRows, ...restRows, ...poolRows, ...gymRows].reduce((s, r) => s + (Number(r.amount) || 0), 0);
  const manualIncomeTotal = manualIncome.reduce((s, r) => s + (Number(r.amount) || 0), 0);
  const totalIncome = autoIncome + manualIncomeTotal;
  const cogs = await Sale.find({ status: 'completed' }).lean().then(sales => sales.reduce((sum, s) => sum + (s.items||[]).reduce((a,it)=> a + (Number(it.cost)||0)*(Number(it.qty)||0),0),0));
  const manualExpenseTotal = manualExpenses.reduce((s, r) => s + (Number(r.amount) || 0), 0);
  const totalExpenses = cogs + manualExpenseTotal;
  const openShifts = await Shift.countDocuments({ status: 'open' });
  const pendingPRs = await PurchaseRequest.countDocuments({ approvalStage: 'pending' });
  res.json({ success: true, data: { totalIncome, totalExpenses, netProfit: totalIncome - totalExpenses, openShifts, pendingPRs } });
});

exports.ledger = asyncHandler(async (req, res) => {
  const page = Math.max(1, parseInt(req.query.page, 10) || 1);
  const limit = Math.min(100, Math.max(1, parseInt(req.query.limit, 10) || 50));
  const from = req.query.from, to = req.query.to, type = req.query.type, dept = req.query.department;
  // Build from real sources
  const [roomRows, restRows, poolRows, gymRows, manualIncome, manualExpenses] = await Promise.all([
    aggregateRoomRevenue(from, to),
    aggregateOutletRevenue(from, to, 'restaurant', 'Restaurant'),
    aggregateOutletRevenue(from, to, 'poolbar', 'Pool Bar'),
    aggregateGymRevenue(from, to),
    IncomeEntry.find(from||to||dept||type ? {} : {}).lean(),
    ExpenseEntry.find(from||to ? {} : {}).lean(),
  ]);
  let entries = [];
  for (const r of [...roomRows, ...restRows, ...poolRows, ...gymRows]) {
    if (type && type !== 'income') continue;
    if (dept && r.department !== dept) continue;
    entries.push({ type: 'income', department: r.department, date: r.date, amount: r.amount, description: r.description, source: r.source });
  }
  for (const m of manualIncome) {
    if (type && type !== 'income') continue;
    if (dept && m.department !== dept) continue;
    if (from && m.date < from) continue;
    if (to && m.date > to) continue;
    entries.push({ type: 'income', department: m.department, date: fmtDate(m.date), amount: m.amount, description: m.description, source: 'manual' });
  }
  for (const e of manualExpenses) {
    if (type && type !== 'expense') continue;
    if (from && fmtDate(e.date) < from) continue;
    if (to && fmtDate(e.date) > to) continue;
    entries.push({ type: 'expense', department: e.category, date: fmtDate(e.date), amount: e.amount, description: e.description, source: 'manual' });
  }
  entries.sort((a,b)=> b.date.localeCompare(a.date));
  const total = entries.length;
  const paged = entries.slice((page-1)*limit, page*limit);
  res.json({ success: true, count: paged.length, total, page, pages: Math.ceil(total/limit)||1, data: paged });
});

exports.transactions = asyncHandler(async (req, res) => {
  const page = Math.max(1, parseInt(req.query.page, 10) || 1);
  const limit = Math.min(100, Math.max(1, parseInt(req.query.limit, 10) || 50));
  const [roomRows, restRows, poolRows, gymRows, manualIncome] = await Promise.all([
    aggregateRoomRevenue(null, null),
    aggregateOutletRevenue(null, null, 'restaurant', 'Restaurant'),
    aggregateOutletRevenue(null, null, 'poolbar', 'Pool Bar'),
    aggregateGymRevenue(null, null),
    IncomeEntry.find({}).lean(),
  ]);
  let entries = [];
  for (const r of [...roomRows, ...restRows, ...poolRows, ...gymRows]) entries.push({ type: 'income', department: r.department, date: r.date, amount: r.amount, description: r.description, source: r.source });
  for (const m of manualIncome) entries.push({ type: 'income', department: m.department, date: fmtDate(m.date), amount: m.amount, description: m.description, source: 'manual' });
  entries.sort((a,b)=> b.date.localeCompare(a.date));
  const total = entries.length;
  const paged = entries.slice((page-1)*limit, page*limit);
  res.json({ success: true, count: paged.length, total, page, pages: Math.ceil(total/limit)||1, data: paged });
});

exports.listShifts = asyncHandler(async (req, res) => {
  const shifts = await Shift.find().sort({ date: -1 });
  res.json({ success: true, count: shifts.length, data: shifts });
});

exports.openShift = asyncHandler(async (req, res) => {
  const { key, dept, staff, openingFloat, date } = req.body;
  if (!key || !dept) return res.status(400).json({ success: false, error: 'key and dept are required' });
  const existing = await Shift.findOne({ key, dept });
  if (existing) return res.status(409).json({ success: false, error: `Shift ${key} for ${dept} already exists` });
  const shift = await Shift.create({
    key: String(key).trim(),
    dept: String(dept).trim(),
    staff: staff ? String(staff).trim() : '',
    openingFloat: Math.max(0, Number(openingFloat) || 0),
    date: date ? new Date(date) : new Date(),
    status: 'open',
  });
  res.status(201).json({ success: true, data: shift });
});

async function computeServerExpectedCash(shift) {
  try {
    const key = shift.key;
    const dept = shift.dept;
    let cashTotal = 0;
    // Helper to get Lagos shift key for a date string/Date
    function lagosYMD(d) { try { return new Date(d).toLocaleDateString('sv-SE', { timeZone: 'Africa/Lagos' }); } catch (e) { return new Date(d).toISOString().slice(0,10); } }
    function lagosHour(d) { try { return parseInt(new Intl.DateTimeFormat('en-GB', { timeZone: 'Africa/Lagos', hour: '2-digit', hour12: false }).format(new Date(d)),10); } catch(e){ return new Date(d).getHours(); } }
    function shiftKeyFor(d) {
      const dt = new Date(d);
      const h = lagosHour(dt);
      let base = dt;
      // shiftStart from Config, default 9
      let shiftStart = 9;
      try { const cfg = global.__shiftStartHour; if (typeof cfg === 'number') shiftStart = cfg; } catch(e){}
      if (h < shiftStart) base = new Date(dt.getTime() - 86400000);
      return lagosYMD(base);
    }
    // Try to get shiftStart from Config if available
    let shiftStart = 9;
    try { const Config = require('../models/Config'); const cfg = await Config.findOne().sort({ createdAt: -1 }); if (cfg && typeof cfg.shiftStartHour === 'number') shiftStart = cfg.shiftStartHour; } catch(e){}
    global.__shiftStartHour = shiftStart;
    function isSameShift(dateStr) {
      if (!dateStr) return false;
      const d = new Date(dateStr.length===10 ? dateStr+'T12:00:00' : dateStr);
      return shiftKeyFor(d) === key;
    }

    if (dept === 'Restaurant' || dept === 'Pool Bar') {
      const deptFilter = dept === 'Restaurant' ? 'restaurant' : 'poolbar';
      const sales = await Sale.find({ department: deptFilter, status: 'completed' });
      for (const s of sales) {
        if (s.method !== 'Cash') continue;
        const d = s.createdAt ? lagosYMD(s.createdAt) : null;
        if (!d) continue;
        const sk = shiftKeyFor(s.createdAt);
        if (sk === key) cashTotal += Number(s.total) || 0;
      }
    } else if (dept === 'Front Desk' || dept === 'Rooms & Bookings' || dept === 'Rooms') {
      const bookings = await Booking.find({ guest: { $ne: '' } });
      for (const b of bookings) {
        const payments = b.payments || [];
        for (const p of payments) {
          if (p.mode !== 'Cash') continue;
          const pd = p.date || b.checkin;
          if (!isSameShift(pd)) continue;
          cashTotal += Number(p.amount) || 0;
        }
      }
    } else if (dept === 'Gym') {
      const members = await GymMember.find({});
      for (const m of members) {
        for (const p of (m.payments || [])) {
          if (p.mode !== 'Cash') continue;
          const pd = p.date || m.startDate;
          if (!isSameShift(pd)) continue;
          cashTotal += Number(p.amount) || 0;
        }
      }
    }
    return (Number(shift.openingFloat) || 0) + cashTotal;
  } catch (e) {
    console.error('[reconcile] computeServerExpectedCash failed', e.message);
    return null;
  }
}
exports.reconcileShift = asyncHandler(async (req, res) => {
  const { actualCash, notes, actor, type } = req.body;
  const actual = Number(actualCash) || 0;
  const shiftDoc = await Shift.findById(req.params.id);
  if (!shiftDoc) return res.status(404).json({ success: false, error: 'Shift not found' });
  let expected = await computeServerExpectedCash(shiftDoc);
  if (expected === null || isNaN(expected)) {
    // fallback to client value if server compute fails, but log
    expected = Number(req.body.expectedCash) || 0;
    console.warn('[reconcile] fallback to client expectedCash', expected);
  } else if (req.body.expectedCash !== undefined && Math.abs(Number(req.body.expectedCash) - expected) > 0.01) {
    console.warn(`[reconcile] client expectedCash ${req.body.expectedCash} != server ${expected} for shift ${shiftDoc.key}/${shiftDoc.dept}`);
  }
  const logEntry = {
    actor: actor || (req.user ? req.user.name : ''),
    actualCash: actual,
    expectedCash: expected,
    variance: actual - expected,
    notes: notes || '',
    type: type === 'correction' ? 'correction' : 'initial',
    date: new Date(),
  };
  const shift = await Shift.findByIdAndUpdate(
    req.params.id,
    {
      actualCash: actual, expectedCash: expected, variance: actual - expected,
      status: 'reconciled', notes: notes || '',
      $push: { reconciliationLog: logEntry },
    },
    { new: true, runValidators: true }
  );
  if (!shift) return res.status(404).json({ success: false, error: 'Shift not found' });
  res.json({ success: true, data: shift });
});

/* ── Procurement Finance Review — accountant sees/approves without entering procurement module ── */
function accountingActor(req) {
  return (req.user && (req.user.name || req.user.role)) || 'Accountant';
}
function isAccountantActor(req) {
  const role = String(req.user && req.user.role || '').toLowerCase();
  if (role === 'admin') return true;
  const privType = String(req.user && req.user.privileges && req.user.privileges.type || '').toLowerCase();
  return role === 'accountant' || privType === 'accountant';
}
function todayISO() { return new Date().toISOString().split('T')[0]; }

exports.listProcurementPending = asyncHandler(async (req, res) => {
  const prs = await PurchaseRequest.find({ approvalStage: 'pending' }).sort({ createdAt: -1 });
  res.json({ success: true, count: prs.length, data: prs });
});

exports.approveProcurement = asyncHandler(async (req, res) => {
  const pr = await PurchaseRequest.findOne({ id: req.params.id });
  if (!pr) throw new ApiError(404, 'Purchase request not found');
  if (pr.approvalStage !== 'pending') throw new ApiError(400, `Cannot approve from stage: ${pr.approvalStage}`);
  if (!isAccountantActor(req)) throw new ApiError(403, `Only Accountant can approve at the 'pending' stage`);
  pr.approvalStage = 'accountant';
  pr.status = 'accountant';
  pr.history.push({ date: todayISO(), action: 'Accountant approved', by: accountingActor(req), note: (req.body && req.body.note) || '', stage: 'accountant' });
  await pr.save();
  res.json({ success: true, data: pr });
});

exports.rejectProcurement = asyncHandler(async (req, res) => {
  const pr = await PurchaseRequest.findOne({ id: req.params.id });
  if (!pr) throw new ApiError(404, 'Purchase request not found');
  if (pr.approvalStage !== 'pending') throw new ApiError(400, `Cannot reject from stage: ${pr.approvalStage}`);
  if (!isAccountantActor(req)) throw new ApiError(403, `Only Accountant can reject at the 'pending' stage`);
  const note = (req.body && (req.body.note || req.body.reason)) || '';
  if (!String(note).trim()) throw new ApiError(400, 'A rejection reason is required');
  pr.approvalStage = 'rejected';
  pr.status = 'rejected';
  pr.rejectReason = String(note).trim();
  pr.history.push({ date: todayISO(), action: 'Rejected by Accountant', by: accountingActor(req), note: String(note).trim(), stage: 'rejected' });
  await pr.save();
  res.json({ success: true, data: pr });
});

exports.procurementPnl = asyncHandler(async (req, res) => {
  const { from, to } = req.query;

  // Gather all sales with procurementId items
  const salesMatch = { status: 'completed' };
  if (from || to) {
    salesMatch.createdAt = {};
    if (from) salesMatch.createdAt.$gte = new Date(from);
    if (to) salesMatch.createdAt.$lte = new Date(to + 'T23:59:59.999Z');
  }
  const sales = await Sale.find(salesMatch);

  // Group revenue by procurementId
  const revByProc = {};
  for (const sale of sales) {
    for (const item of (sale.items || [])) {
      const pid = item.procurementId || '';
      if (!pid) continue;
      if (!revByProc[pid]) revByProc[pid] = { revenue: 0, cost: 0, sales: 0 };
      revByProc[pid].revenue += (Number(item.price) || 0) * (Number(item.qty) || 0);
      revByProc[pid].cost += (Number(item.cost) || 0) * (Number(item.qty) || 0);
      revByProc[pid].sales += 1;
    }
  }

  // Look up PO details for these procurementIds
  const procIds = Object.keys(revByProc);
  const prs = await PurchaseRequest.find({ id: { $in: procIds } });
  const prMap = {};
  for (const pr of prs) prMap[pr.id] = pr;

  const rows = procIds.map(pid => {
    const pr = prMap[pid];
    const data = revByProc[pid];
    return {
      procurementId: pid,
      poNo: pr ? (pr.poNo || pr.prNo || '') : '',
      supplier: pr ? (pr.supplier || '') : '',
      description: pr ? (pr.description || pr.items?.map(i => i.name).join(', ') || '') : '',
      totalCost: pr ? (pr.totalAmount || 0) : data.cost,
      revenue: data.revenue,
      profit: (pr ? (pr.totalAmount || 0) : data.cost) > 0
        ? data.revenue - (pr.totalAmount || 0)
        : data.revenue - data.cost,
      salesCount: data.sales,
    };
  }).sort((a, b) => b.revenue - a.revenue);

  const totalRevenue = rows.reduce((s, r) => s + r.revenue, 0);
  const totalCost = rows.reduce((s, r) => s + r.totalCost, 0);

  res.json({ success: true, rows, totalRevenue, totalCost, netProfit: totalRevenue - totalCost });
});
