const Booking = require('../models/Booking');
const Sale = require('../models/Sale');
const GymMember = require('../models/GymMember');
const IncomeEntry = require('../models/IncomeEntry');
const ExpenseEntry = require('../models/ExpenseEntry');
const LedgerEntry = require('../models/LedgerEntry');
const Shift = require('../models/Shift');
const PurchaseRequest = require('../models/PurchaseRequest');
const asyncHandler = require('../middleware/asyncHandler');

function fmtDate(d) {
  if (!d) return new Date().toISOString().split('T')[0];
  try { return new Date(d).toISOString().split('T')[0]; } catch (e) { return String(d); }
}

async function aggregateRoomRevenue(from, to) {
  const match = { guest: { $ne: '' }, status: { $in: ['checkedin', 'checkout'] } };
  if (from || to) {
    match.checkin = {};
    if (from) match.checkin.$gte = from;
    if (to) match.checkin.$lte = to;
  }
  const bookings = await Booking.find(match);
  return bookings.map(b => {
    const paid = (b.payments || []).reduce((s, p) => s + (Number(p.amount) || 0), 0) || b.paid || 0;
    const method = (b.payments && b.payments.length) ? b.payments[b.payments.length - 1].method : (b.payMethod || '');
    return {
      id: 'auto-room-' + b.room + '-' + (b.checkin || '').replace(/-/g, ''),
      date: b.checkin || fmtDate(b.createdAt || Date.now()),
      department: 'Rooms & Bookings',
      description: 'Room ' + b.room + ' — ' + b.guest,
      amount: paid,
      method: method,
      recordedBy: b.recordedBy || 'System',
      autoGenerated: true,
      source: 'booking',
    };
  }).filter(e => e.amount > 0);
}

async function aggregateOutletRevenue(from, to, sourceName, deptLabel) {
  const match = { source: sourceName, status: 'completed' };
  if (from || to) {
    match.createdAt = {};
    if (from) match.createdAt.$gte = new Date(from);
    if (to) match.createdAt.$lte = new Date(to + 'T23:59:59.999Z');
  }
  const sales = await Sale.find(match);
  return sales.map(s => {
    const totalProcurementCost = (s.items || []).reduce((sum, item) => {
      return sum + (Number(item.cost) || 0) * (Number(item.qty) || 0);
    }, 0);
    return {
      id: 'auto-' + sourceName + '-' + s._id,
      date: fmtDate(s.createdAt),
      department: deptLabel,
      description: (s.items || []).map(i => i.name + ' ×' + i.qty).join(', ') || deptLabel + ' sale',
      amount: s.total || 0,
      method: s.method || '',
      recordedBy: s.waiter || s.staff || 'System',
      autoGenerated: true,
      source: sourceName,
      procurementIds: [...new Set((s.items || []).map(i => i.procurementId).filter(Boolean))],
      cost: totalProcurementCost,
    };
  }).filter(e => e.amount > 0);
}

async function aggregateGymRevenue(from, to) {
  const match = {};
  if (from || to) {
    match.startDate = {};
    if (from) match.startDate.$gte = new Date(from);
    if (to) match.startDate.$lte = new Date(to + 'T23:59:59.999Z');
  }
  const members = await GymMember.find(match);
  return members.map(m => {
    const paid = (m.payments || []).reduce((s, p) => s + (Number(p.amount) || 0), 0) || 0;
    const method = (m.payments && m.payments.length) ? m.payments[m.payments.length - 1].mode : 'Cash';
    return {
      id: 'auto-gym-' + (m._id || '').toString().slice(-8),
      date: fmtDate(m.startDate || Date.now()),
      department: 'Gym',
      description: 'Membership — ' + m.name + (m.planName ? ' (' + m.planName + ')' : ''),
      amount: paid,
      method: method,
      recordedBy: 'Gym Attendant',
      autoGenerated: true,
      source: 'gym',
    };
  }).filter(e => e.amount > 0);
}

exports.pnl = asyncHandler(async (req, res) => {
  const { from, to, mode } = req.query;
  const isShift = mode !== 'calendar';

  // Get shift start hour from Config
  let shiftStart = 9;
  try {
    const Config = require('../models/Config');
    const cfg = await Config.findOne();
    if (cfg && typeof cfg.shiftStartHour === 'number') shiftStart = cfg.shiftStartHour;
  } catch (_) {}

  function shiftKey(dateStr) {
    if (!isShift) return dateStr;
    const d = new Date(dateStr);
    if (isNaN(d.getTime())) return dateStr;
    if (d.getHours() < shiftStart) d.setDate(d.getDate() - 1);
    return fmtDate(d);
  }

  const [roomIncome, restIncome, poolIncome, gymIncome, manualIncome, expenses, prs] = await Promise.all([
    aggregateRoomRevenue(from, to),
    aggregateOutletRevenue(from, to, 'Restaurant', 'Restaurant'),
    aggregateOutletRevenue(from, to, 'Poolbar', 'Pool Bar'),
    aggregateGymRevenue(from, to),
    IncomeEntry.find({ autoGenerated: { $ne: true } }).sort({ date: -1 }),
    ExpenseEntry.find().sort({ date: -1 }),
    PurchaseRequest.find({ approvalStage: { $in: ['fulfilled', 'sent_to_store'] } }).sort({ createdAt: -1 }),
  ]);

  // ── Income: group by shift/calendar day + department ──
  const DEPT_MAP = { 'Rooms & Bookings': 'Front Desk', 'Restaurant': 'Restaurant', 'Pool Bar': 'Pool Bar', 'Gym': 'Gym' };
  const incomeRows = [...roomIncome, ...restIncome, ...poolIncome, ...gymIncome, ...manualIncome.map(e => ({
    date: fmtDate(e.date), department: e.department || 'Other', amount: e.amount || 0, autoGenerated: false,
  }))];

  const incByDate = {};
  for (const row of incomeRows) {
    if (!row.amount || row.amount <= 0) continue;
    const key = shiftKey(row.date);
    const dept = DEPT_MAP[row.department] || row.department || 'Other';
    if (!incByDate[key]) incByDate[key] = { Front Desk: 0, Restaurant: 0, 'Pool Bar': 0, Gym: 0, Other: 0, total: 0 };
    incByDate[key][dept] = (incByDate[key][dept] || 0) + row.amount;
    incByDate[key].total += row.amount;
  }

  const income = Object.entries(incByDate)
    .map(([date, depts]) => ({ date, ...depts }))
    .sort((a, b) => a.date.localeCompare(b.date));

  // ── Expenses: procurement costs + manual expenses ──
  const procByDate = {};
  for (const pr of prs) {
    const key = shiftKey(fmtDate(pr.createdAt));
    if (!procByDate[key]) procByDate[key] = 0;
    procByDate[key] += Number(pr.totalAmount) || 0;
  }

  const manualExpByDate = {};
  for (const e of expenses) {
    const key = shiftKey(fmtDate(e.date));
    if (!manualExpByDate[key]) manualExpByDate[key] = 0;
    manualExpByDate[key] += Number(e.amount) || 0;
  }

  const allDates = [...new Set([...Object.keys(procByDate), ...Object.keys(manualExpByDate)])];
  const expensesOut = allDates.map(date => ({
    date,
    procurement: procByDate[date] || 0,
    manual: manualExpByDate[date] || 0,
    total: (procByDate[date] || 0) + (manualExpByDate[date] || 0),
  })).sort((a, b) => a.date.localeCompare(b.date));

  const totalIncome = income.reduce((s, r) => s + r.total, 0);
  const totalExpenses = expensesOut.reduce((s, r) => s + r.total, 0);

  res.json({ success: true, income, expenses: expensesOut, totalIncome, totalExpenses });
});

exports.addIncome = asyncHandler(async (req, res) => {
  const entry = await IncomeEntry.create({
    date: req.body.date,
    department: req.body.department,
    description: req.body.description,
    amount: Number(req.body.amount) || 0,
    method: req.body.method || '',
    recordedBy: req.body.recordedBy || (req.user ? req.user.name : 'Accountant'),
    autoGenerated: false,
    source: 'manual',
  });
  res.status(201).json({
    success: true,
    data: {
      id: entry._id.toString(),
      date: fmtDate(entry.date),
      department: entry.department,
      description: entry.description,
      amount: entry.amount,
      method: entry.method,
      recordedBy: entry.recordedBy,
      autoGenerated: false,
      source: 'manual',
    },
  });
});

exports.updateIncome = asyncHandler(async (req, res) => {
  const entry = await IncomeEntry.findByIdAndUpdate(
    req.params.id,
    { date: req.body.date, department: req.body.department, description: req.body.description, amount: Number(req.body.amount), method: req.body.method || '', recordedBy: req.body.recordedBy },
    { new: true, runValidators: true }
  );
  if (!entry) return res.status(404).json({ success: false, error: 'Income entry not found' });
  res.json({
    success: true,
    data: {
      id: entry._id.toString(),
      date: fmtDate(entry.date),
      department: entry.department,
      description: entry.description,
      amount: entry.amount,
      method: entry.method,
      recordedBy: entry.recordedBy,
      autoGenerated: false,
      source: 'manual',
    },
  });
});

exports.deleteIncome = asyncHandler(async (req, res) => {
  const entry = await IncomeEntry.findByIdAndDelete(req.params.id);
  if (!entry) return res.status(404).json({ success: false, error: 'Income entry not found' });
  res.json({ success: true, message: 'Income entry deleted' });
});

exports.addExpense = asyncHandler(async (req, res) => {
  const entry = await ExpenseEntry.create({
    date: req.body.date,
    category: req.body.category,
    description: req.body.description,
    amount: Number(req.body.amount) || 0,
    recordedBy: req.body.recordedBy || (req.user ? req.user.name : 'Accountant'),
  });
  res.status(201).json({
    success: true,
    data: {
      id: entry._id.toString(),
      date: fmtDate(entry.date),
      category: entry.category,
      description: entry.description,
      amount: entry.amount,
      recordedBy: entry.recordedBy,
    },
  });
});

exports.updateExpense = asyncHandler(async (req, res) => {
  const entry = await ExpenseEntry.findByIdAndUpdate(
    req.params.id,
    { date: req.body.date, category: req.body.category, description: req.body.description, amount: Number(req.body.amount), recordedBy: req.body.recordedBy },
    { new: true, runValidators: true }
  );
  if (!entry) return res.status(404).json({ success: false, error: 'Expense entry not found' });
  res.json({
    success: true,
    data: {
      id: entry._id.toString(),
      date: fmtDate(entry.date),
      category: entry.category,
      description: entry.description,
      amount: entry.amount,
      recordedBy: entry.recordedBy,
    },
  });
});

exports.deleteExpense = asyncHandler(async (req, res) => {
  const entry = await ExpenseEntry.findByIdAndDelete(req.params.id);
  if (!entry) return res.status(404).json({ success: false, error: 'Expense entry not found' });
  res.json({ success: true, message: 'Expense entry deleted' });
});

exports.summary = asyncHandler(async (req, res) => {
  const incomeAgg = await LedgerEntry.aggregate([
    { $match: { type: 'income' } },
    { $group: { _id: null, total: { $sum: '$amount' } } },
  ]);
  const expenseAgg = await LedgerEntry.aggregate([
    { $match: { type: 'expense' } },
    { $group: { _id: null, total: { $sum: '$amount' } } },
  ]);
  const totalIncome = incomeAgg[0]?.total || 0;
  const totalExpenses = expenseAgg[0]?.total || 0;
  const openShifts = await Shift.countDocuments({ status: 'open' });
  const pendingPRs = await PurchaseRequest.countDocuments({ status: 'pending' });
  res.json({ success: true, data: { totalIncome, totalExpenses, netProfit: totalIncome - totalExpenses, openShifts, pendingPRs } });
});

exports.ledger = asyncHandler(async (req, res) => {
  const filter = {};
  if (req.query.type) filter.type = req.query.type;
  if (req.query.department) filter.department = req.query.department;
  if (req.query.from || req.query.to) {
    filter.date = {};
    if (req.query.from) filter.date.$gte = new Date(req.query.from);
    if (req.query.to) filter.date.$lte = new Date(req.query.to);
  }
  const entries = await LedgerEntry.find(filter).sort({ date: -1 });
  res.json({ success: true, count: entries.length, data: entries });
});

exports.transactions = asyncHandler(async (req, res) => {
  const entries = await LedgerEntry.find().sort({ date: -1 });
  res.json({ success: true, count: entries.length, data: entries });
});

exports.listShifts = asyncHandler(async (req, res) => {
  const shifts = await Shift.find().sort({ date: -1 });
  res.json({ success: true, count: shifts.length, data: shifts });
});

exports.openShift = asyncHandler(async (req, res) => {
  const shift = await Shift.create(req.body);
  res.status(201).json({ success: true, data: shift });
});

exports.reconcileShift = asyncHandler(async (req, res) => {
  const { actualCash, expectedCash, notes, actor, type } = req.body;
  const actual = Number(actualCash) || 0;
  const expected = Number(expectedCash) || 0;
  const logEntry = {
    actor: actor || (req.user ? req.user.name : ''),
    actualCash: actual,
    expectedCash: expected,
    variance: actual - expected,
    notes: notes || '',
    type: type === 'correction' ? 'correction' : 'initial',
    date: new Date(),
  };
  const shift = await Shift.findByIdAndUpdate(
    req.params.id,
    {
      actualCash: actual, expectedCash: expected, variance: actual - expected,
      status: 'reconciled', notes: notes || '',
      $push: { reconciliationLog: logEntry },
    },
    { new: true, runValidators: true }
  );
  if (!shift) return res.status(404).json({ success: false, error: 'Shift not found' });
  res.json({ success: true, data: shift });
});

exports.procurementPnl = asyncHandler(async (req, res) => {
  const { from, to } = req.query;

  // Gather all sales with procurementId items
  const salesMatch = { status: 'completed' };
  if (from || to) {
    salesMatch.createdAt = {};
    if (from) salesMatch.createdAt.$gte = new Date(from);
    if (to) salesMatch.createdAt.$lte = new Date(to + 'T23:59:59.999Z');
  }
  const sales = await Sale.find(salesMatch);

  // Group revenue by procurementId
  const revByProc = {};
  for (const sale of sales) {
    for (const item of (sale.items || [])) {
      const pid = item.procurementId || '';
      if (!pid) continue;
      if (!revByProc[pid]) revByProc[pid] = { revenue: 0, cost: 0, sales: 0 };
      revByProc[pid].revenue += (Number(item.price) || 0) * (Number(item.qty) || 0);
      revByProc[pid].cost += (Number(item.cost) || 0) * (Number(item.qty) || 0);
      revByProc[pid].sales += 1;
    }
  }

  // Look up PO details for these procurementIds
  const procIds = Object.keys(revByProc);
  const prs = await PurchaseRequest.find({ id: { $in: procIds } });
  const prMap = {};
  for (const pr of prs) prMap[pr.id] = pr;

  const rows = procIds.map(pid => {
    const pr = prMap[pid];
    const data = revByProc[pid];
    return {
      procurementId: pid,
      poNo: pr ? (pr.poNo || pr.prNo || '') : '',
      supplier: pr ? (pr.supplier || '') : '',
      description: pr ? (pr.description || pr.items?.map(i => i.name).join(', ') || '') : '',
      totalCost: pr ? (pr.totalAmount || 0) : data.cost,
      revenue: data.revenue,
      profit: (pr ? (pr.totalAmount || 0) : data.cost) > 0
        ? data.revenue - (pr.totalAmount || 0)
        : data.revenue - data.cost,
      salesCount: data.sales,
    };
  }).sort((a, b) => b.revenue - a.revenue);

  const totalRevenue = rows.reduce((s, r) => s + r.revenue, 0);
  const totalCost = rows.reduce((s, r) => s + r.totalCost, 0);

  res.json({ success: true, rows, totalRevenue, totalCost, netProfit: totalRevenue - totalCost });
});
