const Booking = require('../models/Booking');
const Sale = require('../models/Sale');
const GymMember = require('../models/GymMember');
const IncomeEntry = require('../models/IncomeEntry');
const ExpenseEntry = require('../models/ExpenseEntry');
const LedgerEntry = require('../models/LedgerEntry');
const Shift = require('../models/Shift');
const PurchaseRequest = require('../models/PurchaseRequest');
const asyncHandler = require('../middleware/asyncHandler');
const { ApiError } = require('../middleware/errorHandler');

function fmtDate(d) {
  if (!d) return new Date().toISOString().split('T')[0];
  try { return new Date(d).toISOString().split('T')[0]; } catch (e) { return String(d); }
}

function lagosDate(d) {
  if (!d) d = new Date();
  try {
    return new Date(d).toLocaleDateString('sv-SE', { timeZone: 'Africa/Lagos' });
  } catch (e) { return fmtDate(d); }
}

function parsePaymentDate(str) {
  if (!str) return '';
  // Already YYYY-MM-DD
  if (/^\d{4}-\d{2}-\d{2}/.test(str)) return str.slice(0, 10);
  // DD/MM/YY or DD/MM/YYYY from todayDDMMYY()
  const parts = str.split('/');
  if (parts.length === 3) {
    const dd = parts[0].padStart(2, '0');
    const mm = parts[1].padStart(2, '0');
    let yy = parts[2];
    if (yy.length === 2) yy = '20' + yy;
    return yy + '-' + mm + '-' + dd;
  }
  // Try Date parse as fallback
  const d = new Date(str);
  if (!isNaN(d.getTime())) return fmtDate(d);
  return str;
}

async function aggregateRoomRevenue(from, to) {
  // Fetch all bookings with a guest (non-vacant)
  const bookings = await Booking.find({ guest: { $ne: '' } });
  return bookings.map(b => {
    const payments = b.payments || [];
    const paid = payments.reduce((s, p) => s + (Number(p.amount) || 0), 0) || b.paid || 0;
    if (paid <= 0) return null;

    // Use the LAST payment date as the revenue date
    const lastPayment = payments.length ? payments[payments.length - 1] : null;
    const method = lastPayment ? lastPayment.mode : (b.payMethod || '');
    const rawDate = (lastPayment && lastPayment.date) || b.checkin || lagosDate(b.createdAt || Date.now());
    const payDate = parsePaymentDate(rawDate) || lagosDate(b.createdAt || Date.now());

    // Apply date filter on the payment date (not checkin)
    if (from && payDate < from) return null;
    if (to && payDate > to) return null;

    return {
      id: 'auto-room-' + b.room + '-' + payDate,
      date: payDate,
      department: 'Rooms & Bookings',
      description: 'Room ' + b.room + ' — ' + b.guest,
      amount: paid,
      method: method,
      recordedBy: b.recordedBy || 'System',
      autoGenerated: true,
      source: 'booking',
    };
  }).filter(Boolean);
}

async function aggregateOutletRevenue(from, to, deptFilter, deptLabel) {
  const match = { department: deptFilter, status: 'completed' };
  if (from || to) {
    match.createdAt = {};
    if (from) match.createdAt.$gte = new Date(from);
    if (to) match.createdAt.$lte = new Date(to + 'T23:59:59.999Z');
  }
  const sales = await Sale.find(match);
  return sales.map(s => {
    const totalProcurementCost = (s.items || []).reduce((sum, item) => {
      return sum + (Number(item.cost) || 0) * (Number(item.qty) || 0);
    }, 0);
    return {
      id: 'auto-' + deptFilter + '-' + s._id,
      date: lagosDate(s.createdAt),
      department: deptLabel,
      description: (s.items || []).map(i => i.name + ' ×' + i.qty).join(', ') || deptLabel + ' sale',
      amount: s.total || 0,
      method: s.method || '',
      recordedBy: s.waiter || s.staff || 'System',
      autoGenerated: true,
      source: deptFilter,
      procurementIds: [...new Set((s.items || []).map(i => i.procurementId).filter(Boolean))],
      cost: totalProcurementCost,
    };
  }).filter(e => e.amount > 0);
}

async function aggregateGymRevenue(from, to) {
  const match = {};
  if (from || to) {
    match.startDate = {};
    if (from) match.startDate.$gte = new Date(from);
    if (to) match.startDate.$lte = new Date(to + 'T23:59:59.999Z');
  }
  const members = await GymMember.find(match);
  return members.map(m => {
    const paid = (m.payments || []).reduce((s, p) => s + (Number(p.amount) || 0), 0) || 0;
    const method = (m.payments && m.payments.length) ? m.payments[m.payments.length - 1].mode : 'Cash';
    return {
      id: 'auto-gym-' + (m._id || '').toString().slice(-8),
      date: lagosDate(m.startDate || Date.now()),
      department: 'Gym',
      description: 'Membership — ' + m.name + (m.planName ? ' (' + m.planName + ')' : ''),
      amount: paid,
      method: method,
      recordedBy: 'Gym Attendant',
      autoGenerated: true,
      source: 'gym',
    };
  }).filter(e => e.amount > 0);
}

exports.pnl = asyncHandler(async (req, res) => {
  const { from, to, mode } = req.query;
  const isShift = mode !== 'calendar';

  // Get shift start hour from Config
  let shiftStart = 9;
  try {
    const Config = require('../models/Config');
    const cfg = await Config.findOne();
    if (cfg && typeof cfg.shiftStartHour === 'number') shiftStart = cfg.shiftStartHour;
  } catch (err) {
    console.error('[Accounting] Failed to load shift start hour from Config:', err.message);
  }

  function shiftKey(dateStr) {
    if (!isShift) return dateStr;
    const d = /^\d{4}-\d{2}-\d{2}$/.test(dateStr) ? new Date(dateStr + 'T12:00:00') : new Date(dateStr);
    if (isNaN(d.getTime())) return dateStr;
    if (d.getHours() < shiftStart) d.setDate(d.getDate() - 1);
    return lagosDate(d);
  }

  const safeAgg = (fn, label) => fn().catch(err => { console.error(`[Accounting] ${label} aggregation failed:`, err.message); return []; });

  // Manual income: apply date filter
  const manualMatch = { autoGenerated: { $ne: true } };
  if (from || to) {
    manualMatch.date = {};
    if (from) manualMatch.date.$gte = from;
    if (to) manualMatch.date.$lte = to;
  }
  // Manual expenses: apply date filter
  const expenseMatch = {};
  if (from || to) {
    expenseMatch.date = {};
    if (from) expenseMatch.date.$gte = from;
    if (to) expenseMatch.date.$lte = to;
  }

  const [roomIncome, restIncome, poolIncome, gymIncome, manualIncome, expenses, prs] = await Promise.all([
    safeAgg(() => aggregateRoomRevenue(from, to), 'Room Revenue'),
    safeAgg(() => aggregateOutletRevenue(from, to, 'restaurant', 'Restaurant'), 'Restaurant Revenue'),
    safeAgg(() => aggregateOutletRevenue(from, to, 'poolbar', 'Pool Bar'), 'Pool Bar Revenue'),
    safeAgg(() => aggregateGymRevenue(from, to), 'Gym Revenue'),
    IncomeEntry.find(manualMatch).sort({ date: -1 }).catch(err => { console.error('[Accounting] Manual income query failed:', err.message); return []; }),
    ExpenseEntry.find(expenseMatch).sort({ date: -1 }).catch(err => { console.error('[Accounting] Expense query failed:', err.message); return []; }),
    PurchaseRequest.find({ approvalStage: { $in: ['fulfilled', 'sent_to_store'] }, ...(from || to ? { createdAt: { ...(from ? { $gte: new Date(from) } : {}), ...(to ? { $lte: new Date(to + 'T23:59:59.999Z') } : {}) } } : {}) }).sort({ createdAt: -1 }).catch(err => { console.error('[Accounting] PurchaseRequest query failed:', err.message); return []; }),
  ]);

  // ── Income: aggregate to one row per (shift/calendar day, department) ──
  console.log('[Accounting pnl] raw counts:', { roomIncome: roomIncome.length, restIncome: restIncome.length, poolIncome: poolIncome.length, gymIncome: gymIncome.length, manualIncome: manualIncome.length, mode: isShift ? 'shift' : 'calendar', from: from || '-', to: to || '-' });
  roomIncome.slice(0,3).forEach(r => console.log('[Accounting pnl] roomIncome sample:', JSON.stringify(r)));
  restIncome.slice(0,3).forEach(r => console.log('[Accounting pnl] restIncome sample:', JSON.stringify(r)));
  const DEPT_MAP = { 'Rooms & Bookings': 'Front Desk', 'Restaurant': 'Restaurant', 'Pool Bar': 'Pool Bar', 'Gym': 'Gym' };
  const incomeRows = [...roomIncome, ...restIncome, ...poolIncome, ...gymIncome, ...manualIncome.map(e => ({
    id: e._id ? e._id.toString() : e.id, date: fmtDate(e.date), department: e.department || 'Other', amount: e.amount || 0, autoGenerated: false, source: e.source || 'manual', description: e.description || '', method: e.method || '', recordedBy: e.recordedBy || '',
  }))];
  console.log('[Accounting pnl] incomeRows total:', incomeRows.length);

  const grouped = {};
  for (const r of incomeRows) {
    if (!r.amount || r.amount <= 0) continue;
    const dept = DEPT_MAP[r.department] || r.department || 'Other';
    const d = shiftKey(r.date);
    const key = d + '|' + dept;
    if (!grouped[key]) {
      grouped[key] = { id: key, date: d, department: dept, amount: 0, source: r.source || (dept === 'Front Desk' ? 'booking' : dept === 'Restaurant' ? 'Restaurant' : dept === 'Pool Bar' ? 'Poolbar' : dept === 'Gym' ? 'gym' : 'manual'), description: '', method: '', recordedBy: '', autoGenerated: r.autoGenerated !== undefined ? r.autoGenerated : true };
    }
    grouped[key].amount += Number(r.amount) || 0;
  }
  const income = Object.values(grouped).sort((a, b) => b.date.localeCompare(a.date) || a.department.localeCompare(b.department));
  console.log('[Accounting pnl] grouped income:', income.length, income.slice(0,5).map(r => r.date + '|' + r.department + '=' + r.amount));

  // ── Expenses: one row per type per shift/calendar day ──
  const procByDate = {};
  for (const pr of prs) {
    const key = shiftKey(lagosDate(pr.createdAt));
    if (!procByDate[key]) procByDate[key] = 0;
    procByDate[key] += Number(pr.totalAmount) || 0;
  }

  const manualExpByDate = {};
  for (const e of expenses) {
    const key = shiftKey(fmtDate(e.date));
    if (!manualExpByDate[key]) manualExpByDate[key] = 0;
    manualExpByDate[key] += Number(e.amount) || 0;
  }

  const allDates = [...new Set([...Object.keys(procByDate), ...Object.keys(manualExpByDate)])];
  const expensesOut = allDates.map(date => ({
    date,
    procurement: procByDate[date] || 0,
    manual: manualExpByDate[date] || 0,
    total: (procByDate[date] || 0) + (manualExpByDate[date] || 0),
  })).sort((a, b) => b.date.localeCompare(a.date));

  const totalIncome = income.reduce((s, r) => s + r.amount, 0);
  const totalExpenses = expensesOut.reduce((s, r) => s + r.total, 0);

  res.json({ success: true, income, expenses: expensesOut, totalIncome, totalExpenses });
});

exports.addIncome = asyncHandler(async (req, res) => {
  const entry = await IncomeEntry.create({
    date: req.body.date,
    department: req.body.department,
    description: req.body.description,
    amount: Number(req.body.amount) || 0,
    method: req.body.method || '',
    recordedBy: req.body.recordedBy || (req.user ? req.user.name : 'Accountant'),
    autoGenerated: false,
    source: 'manual',
  });
  res.status(201).json({
    success: true,
    data: {
      id: entry._id.toString(),
      date: fmtDate(entry.date),
      department: entry.department,
      description: entry.description,
      amount: entry.amount,
      method: entry.method,
      recordedBy: entry.recordedBy,
      autoGenerated: false,
      source: 'manual',
    },
  });
});

exports.updateIncome = asyncHandler(async (req, res) => {
  const entry = await IncomeEntry.findByIdAndUpdate(
    req.params.id,
    { date: req.body.date, department: req.body.department, description: req.body.description, amount: Number(req.body.amount), method: req.body.method || '', recordedBy: req.body.recordedBy },
    { new: true, runValidators: true }
  );
  if (!entry) return res.status(404).json({ success: false, error: 'Income entry not found' });
  res.json({
    success: true,
    data: {
      id: entry._id.toString(),
      date: fmtDate(entry.date),
      department: entry.department,
      description: entry.description,
      amount: entry.amount,
      method: entry.method,
      recordedBy: entry.recordedBy,
      autoGenerated: false,
      source: 'manual',
    },
  });
});

exports.deleteIncome = asyncHandler(async (req, res) => {
  const entry = await IncomeEntry.findByIdAndDelete(req.params.id);
  if (!entry) return res.status(404).json({ success: false, error: 'Income entry not found' });
  res.json({ success: true, message: 'Income entry deleted' });
});

exports.addExpense = asyncHandler(async (req, res) => {
  const entry = await ExpenseEntry.create({
    date: req.body.date,
    category: req.body.category,
    description: req.body.description,
    amount: Number(req.body.amount) || 0,
    recordedBy: req.body.recordedBy || (req.user ? req.user.name : 'Accountant'),
  });
  res.status(201).json({
    success: true,
    data: {
      id: entry._id.toString(),
      date: fmtDate(entry.date),
      category: entry.category,
      description: entry.description,
      amount: entry.amount,
      recordedBy: entry.recordedBy,
    },
  });
});

exports.updateExpense = asyncHandler(async (req, res) => {
  const entry = await ExpenseEntry.findByIdAndUpdate(
    req.params.id,
    { date: req.body.date, category: req.body.category, description: req.body.description, amount: Number(req.body.amount), recordedBy: req.body.recordedBy },
    { new: true, runValidators: true }
  );
  if (!entry) return res.status(404).json({ success: false, error: 'Expense entry not found' });
  res.json({
    success: true,
    data: {
      id: entry._id.toString(),
      date: fmtDate(entry.date),
      category: entry.category,
      description: entry.description,
      amount: entry.amount,
      recordedBy: entry.recordedBy,
    },
  });
});

exports.deleteExpense = asyncHandler(async (req, res) => {
  const entry = await ExpenseEntry.findByIdAndDelete(req.params.id);
  if (!entry) return res.status(404).json({ success: false, error: 'Expense entry not found' });
  res.json({ success: true, message: 'Expense entry deleted' });
});

exports.summary = asyncHandler(async (req, res) => {
  const incomeAgg = await LedgerEntry.aggregate([
    { $match: { type: 'income' } },
    { $group: { _id: null, total: { $sum: '$amount' } } },
  ]);
  const expenseAgg = await LedgerEntry.aggregate([
    { $match: { type: 'expense' } },
    { $group: { _id: null, total: { $sum: '$amount' } } },
  ]);
  const totalIncome = incomeAgg[0]?.total || 0;
  const totalExpenses = expenseAgg[0]?.total || 0;
  const openShifts = await Shift.countDocuments({ status: 'open' });
  const pendingPRs = await PurchaseRequest.countDocuments({ status: 'pending' });
  res.json({ success: true, data: { totalIncome, totalExpenses, netProfit: totalIncome - totalExpenses, openShifts, pendingPRs } });
});

exports.ledger = asyncHandler(async (req, res) => {
  const filter = {};
  if (req.query.type) filter.type = req.query.type;
  if (req.query.department) filter.department = req.query.department;
  if (req.query.from || req.query.to) {
    filter.date = {};
    if (req.query.from) filter.date.$gte = new Date(req.query.from);
    if (req.query.to) filter.date.$lte = new Date(req.query.to);
  }
  const entries = await LedgerEntry.find(filter).sort({ date: -1 });
  res.json({ success: true, count: entries.length, data: entries });
});

exports.transactions = asyncHandler(async (req, res) => {
  const entries = await LedgerEntry.find().sort({ date: -1 });
  res.json({ success: true, count: entries.length, data: entries });
});

exports.listShifts = asyncHandler(async (req, res) => {
  const shifts = await Shift.find().sort({ date: -1 });
  res.json({ success: true, count: shifts.length, data: shifts });
});

exports.openShift = asyncHandler(async (req, res) => {
  const shift = await Shift.create(req.body);
  res.status(201).json({ success: true, data: shift });
});

exports.reconcileShift = asyncHandler(async (req, res) => {
  const { actualCash, expectedCash, notes, actor, type } = req.body;
  const actual = Number(actualCash) || 0;
  const expected = Number(expectedCash) || 0;
  const logEntry = {
    actor: actor || (req.user ? req.user.name : ''),
    actualCash: actual,
    expectedCash: expected,
    variance: actual - expected,
    notes: notes || '',
    type: type === 'correction' ? 'correction' : 'initial',
    date: new Date(),
  };
  const shift = await Shift.findByIdAndUpdate(
    req.params.id,
    {
      actualCash: actual, expectedCash: expected, variance: actual - expected,
      status: 'reconciled', notes: notes || '',
      $push: { reconciliationLog: logEntry },
    },
    { new: true, runValidators: true }
  );
  if (!shift) return res.status(404).json({ success: false, error: 'Shift not found' });
  res.json({ success: true, data: shift });
});

/* ── Procurement Finance Review — accountant sees/approves without entering procurement module ── */
function accountingActor(req) {
  return (req.user && (req.user.name || req.user.role)) || 'Accountant';
}
function isAccountantActor(req) {
  const role = String(req.user && req.user.role || '').toLowerCase();
  if (role === 'admin') return true;
  const privType = String(req.user && req.user.privileges && req.user.privileges.type || '').toLowerCase();
  return role === 'accountant' || privType === 'accountant';
}
function todayISO() { return new Date().toISOString().split('T')[0]; }

exports.listProcurementPending = asyncHandler(async (req, res) => {
  const prs = await PurchaseRequest.find({ approvalStage: 'pending' }).sort({ createdAt: -1 });
  res.json({ success: true, count: prs.length, data: prs });
});

exports.approveProcurement = asyncHandler(async (req, res) => {
  const pr = await PurchaseRequest.findOne({ id: req.params.id });
  if (!pr) throw new ApiError(404, 'Purchase request not found');
  if (pr.approvalStage !== 'pending') throw new ApiError(400, `Cannot approve from stage: ${pr.approvalStage}`);
  if (!isAccountantActor(req)) throw new ApiError(403, `Only Accountant can approve at the 'pending' stage`);
  pr.approvalStage = 'accountant';
  pr.status = 'accountant';
  pr.history.push({ date: todayISO(), action: 'Accountant approved', by: accountingActor(req), note: (req.body && req.body.note) || '', stage: 'accountant' });
  await pr.save();
  res.json({ success: true, data: pr });
});

exports.rejectProcurement = asyncHandler(async (req, res) => {
  const pr = await PurchaseRequest.findOne({ id: req.params.id });
  if (!pr) throw new ApiError(404, 'Purchase request not found');
  if (pr.approvalStage !== 'pending') throw new ApiError(400, `Cannot reject from stage: ${pr.approvalStage}`);
  if (!isAccountantActor(req)) throw new ApiError(403, `Only Accountant can reject at the 'pending' stage`);
  const note = (req.body && (req.body.note || req.body.reason)) || '';
  if (!String(note).trim()) throw new ApiError(400, 'A rejection reason is required');
  pr.approvalStage = 'rejected';
  pr.status = 'rejected';
  pr.rejectReason = String(note).trim();
  pr.history.push({ date: todayISO(), action: 'Rejected by Accountant', by: accountingActor(req), note: String(note).trim(), stage: 'rejected' });
  await pr.save();
  res.json({ success: true, data: pr });
});

exports.procurementPnl = asyncHandler(async (req, res) => {
  const { from, to } = req.query;

  // Gather all sales with procurementId items
  const salesMatch = { status: 'completed' };
  if (from || to) {
    salesMatch.createdAt = {};
    if (from) salesMatch.createdAt.$gte = new Date(from);
    if (to) salesMatch.createdAt.$lte = new Date(to + 'T23:59:59.999Z');
  }
  const sales = await Sale.find(salesMatch);

  // Group revenue by procurementId
  const revByProc = {};
  for (const sale of sales) {
    for (const item of (sale.items || [])) {
      const pid = item.procurementId || '';
      if (!pid) continue;
      if (!revByProc[pid]) revByProc[pid] = { revenue: 0, cost: 0, sales: 0 };
      revByProc[pid].revenue += (Number(item.price) || 0) * (Number(item.qty) || 0);
      revByProc[pid].cost += (Number(item.cost) || 0) * (Number(item.qty) || 0);
      revByProc[pid].sales += 1;
    }
  }

  // Look up PO details for these procurementIds
  const procIds = Object.keys(revByProc);
  const prs = await PurchaseRequest.find({ id: { $in: procIds } });
  const prMap = {};
  for (const pr of prs) prMap[pr.id] = pr;

  const rows = procIds.map(pid => {
    const pr = prMap[pid];
    const data = revByProc[pid];
    return {
      procurementId: pid,
      poNo: pr ? (pr.poNo || pr.prNo || '') : '',
      supplier: pr ? (pr.supplier || '') : '',
      description: pr ? (pr.description || pr.items?.map(i => i.name).join(', ') || '') : '',
      totalCost: pr ? (pr.totalAmount || 0) : data.cost,
      revenue: data.revenue,
      profit: (pr ? (pr.totalAmount || 0) : data.cost) > 0
        ? data.revenue - (pr.totalAmount || 0)
        : data.revenue - data.cost,
      salesCount: data.sales,
    };
  }).sort((a, b) => b.revenue - a.revenue);

  const totalRevenue = rows.reduce((s, r) => s + r.revenue, 0);
  const totalCost = rows.reduce((s, r) => s + r.totalCost, 0);

  res.json({ success: true, rows, totalRevenue, totalCost, netProfit: totalRevenue - totalCost });
});
