const mongoose = require('mongoose');

const incomeEntrySchema = new mongoose.Schema({
  date:        { type: Date, default: Date.now },
  department:  { type: String, default: '' },
  description: { type: String, default: '' },
  amount:      { type: Number, default: 0 },
  recordedBy:  { type: String, default: '' },
  autoGenerated: { type: Boolean, default: false },
  source:      { type: String, default: '' },
}, { timestamps: true });

module.exports = mongoose.model('IncomeEntry', incomeEntrySchema);
